heat_template_version: "2015-04-30"

description: "Simple template to deploy a single compute instance"

parameters:
  image:
    type: string
    default: "cirros"
  flavor:
    type: string
    default: "m1.small"
  network:
    type: string
    default: "5522be82-3f60-4af3-88d8-40659176bca8"

resources: 

  MyPort:
    type: OS::Neutron::Port
    properties:
      name: "MyPort"
      network: { get_param: network }

  MyServer:
    type: OS::Nova::Server
    properties:
      name: "MyServer"

      flavor: { get_param: flavor }
      image: { get_param: image }

      networks:
        - port: { get_resource: MyPort }
